using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Typhon.Generators.Telemetry
{
    /// <summary>
    /// Emits <c>TelemetryFlagCatalog.g.cs</c> — the runtime descriptor tree of every telemetry flag (Feature
    /// #522, T3). Consumed in-process by the <c>typhon telemetry</c> CLI to render/resolve/edit
    /// <c>typhon.telemetry.json</c> without parsing the catalog file at runtime. Emitted from the same
    /// <c>telemetry-flags.jsonc</c>, engine-build-only (gated on <c>AssemblyName == "Typhon.Engine"</c>).
    /// </summary>
    [Generator]
    public sealed class TelemetryFlagCatalogGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var catalog = context.AdditionalTextsProvider
                .Where(f => Path.GetFileName(f.Path) == "telemetry-flags.jsonc")
                .Select((f, ct) => f.GetText(ct)?.ToString())
                .Collect();
            var asmName = context.CompilationProvider.Select((c, _) => c.AssemblyName);

            context.RegisterSourceOutput(catalog.Combine(asmName), (spc, pair) =>
            {
                var (texts, assembly) = pair;
                if (assembly != "Typhon.Engine")
                {
                    return;
                }
                var text = texts.FirstOrDefault(t => !string.IsNullOrEmpty(t));
                if (string.IsNullOrEmpty(text))
                {
                    return;
                }
                var cat = TelemetryCatalog.Parse(text);
                if (cat?.Root == null)
                {
                    return;
                }
                spc.AddSource("TelemetryFlagCatalog.g.cs", SourceText.From(Emit(cat), Encoding.UTF8));
            });
        }

        private static readonly Dictionary<string, string> KindEnum = new Dictionary<string, string>
        {
            ["master"] = "Master",
            ["compositeActive"] = "CompositeActive",
            ["rawLeaf"] = "RawLeaf",
            ["subtreeResolved"] = "SubtreeResolved",
            ["group"] = "Group",
        };

        private static string Lit(string s) => s == null ? "null" : "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

        private static string Emit(Catalog cat)
        {
            // Flatten depth-first, recording parent indices.
            var flat = new List<(FlagNode node, int parent, int depth)>();
            void Walk(FlagNode n, int parent, int depth)
            {
                int idx = flat.Count;
                flat.Add((n, parent, depth));
                foreach (var c in n.Children)
                {
                    Walk(c, idx, depth + 1);
                }
            }
            Walk(cat.Root, -1, 0);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// GENERATED by Typhon.Generators.Telemetry.TelemetryFlagCatalogGenerator from telemetry-flags.jsonc — do not edit.");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace Typhon.Engine");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>Kind of a telemetry flag — how its gate is resolved. See the catalog design (#522).</summary>");
            sb.AppendLine("    public enum TelemetryFlagKind");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>The master profiler gate (Typhon:Profiler:Enabled).</summary>");
            sb.AppendLine("        Master,");
            sb.AppendLine("        /// <summary>A master direct child: an Enabled + derived Active pair.</summary>");
            sb.AppendLine("        CompositeActive,");
            sb.AppendLine("        /// <summary>Read raw, not parent-gated (an opt-out firehose gauge; may default true).</summary>");
            sb.AppendLine("        RawLeaf,");
            sb.AppendLine("        /// <summary>Resolved via parent-implies-children (the 10 subtrees).</summary>");
            sb.AppendLine("        SubtreeResolved,");
            sb.AppendLine("        /// <summary>A pure grouping node with no gate field of its own.</summary>");
            sb.AppendLine("        Group,");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>One node of the telemetry flag catalog — its config key, C# gate field, default and tree position.</summary>");
            sb.AppendLine("    public readonly struct TelemetryFlagDescriptor");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>Full config key, e.g. <c>Typhon:Profiler:Concurrency:AccessControl:Contention:Enabled</c>.</summary>");
            sb.AppendLine("        public string Key { get; }");
            sb.AppendLine("        /// <summary>Path below the prefix, colon-joined (empty for the master node).</summary>");
            sb.AppendLine("        public string Path { get; }");
            sb.AppendLine("        /// <summary>Single-segment node name.</summary>");
            sb.AppendLine("        public string Name { get; }");
            sb.AppendLine("        /// <summary>Exact <c>TelemetryConfig</c> gate field name; null for pure grouping nodes.</summary>");
            sb.AppendLine("        public string Field { get; }");
            sb.AppendLine("        /// <summary>User-facing description (docs + CLI tooltips).</summary>");
            sb.AppendLine("        public string Description { get; }");
            sb.AppendLine("        /// <summary>Built-in default (true only for the un-gated firehose gauges).</summary>");
            sb.AppendLine("        public bool Default { get; }");
            sb.AppendLine("        /// <summary>How the gate resolves.</summary>");
            sb.AppendLine("        public TelemetryFlagKind Kind { get; }");
            sb.AppendLine("        /// <summary>Index of the parent node in <see cref=\"TelemetryFlagCatalog.All\"/>, or -1 for the root.</summary>");
            sb.AppendLine("        public int ParentIndex { get; }");
            sb.AppendLine("        /// <summary>Depth from the root (root = 0).</summary>");
            sb.AppendLine("        public int Depth { get; }");
            sb.AppendLine("        /// <summary>Create a descriptor.</summary>");
            sb.AppendLine("        public TelemetryFlagDescriptor(string key, string path, string name, string field, string description, bool @default, TelemetryFlagKind kind, int parentIndex, int depth)");
            sb.AppendLine("        {");
            sb.AppendLine("            Key = key; Path = path; Name = name; Field = field; Description = description; Default = @default; Kind = kind; ParentIndex = parentIndex; Depth = depth;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>The generated, in-memory catalog of every telemetry flag (source of truth: telemetry-flags.jsonc).</summary>");
            sb.AppendLine("    public static class TelemetryFlagCatalog");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>The JSON config prefix all keys share.</summary>");
            sb.AppendLine("        public static string Prefix => " + Lit(cat.Prefix) + ";");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>All flag descriptors in depth-first (parent-before-child) order.</summary>");
            sb.AppendLine("        public static IReadOnlyList<TelemetryFlagDescriptor> All { get; } = new TelemetryFlagDescriptor[]");
            sb.AppendLine("        {");
            foreach (var (node, parent, depth) in flat)
            {
                sb.Append("            new TelemetryFlagDescriptor(");
                sb.Append(Lit(node.Key)).Append(", ");
                sb.Append(Lit(node.Path)).Append(", ");
                sb.Append(Lit(node.Name)).Append(", ");
                sb.Append(Lit(node.Field)).Append(", ");
                sb.Append(Lit(node.Desc)).Append(", ");
                sb.Append(node.Default ? "true" : "false").Append(", ");
                sb.Append("TelemetryFlagKind.").Append(KindEnum.TryGetValue(node.Kind, out var ke) ? ke : "Group").Append(", ");
                sb.Append(parent).Append(", ");
                sb.Append(depth).AppendLine("),");
            }
            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>Indices of the direct children of the node at <paramref name=\"index\"/>, in catalog order.</summary>");
            sb.AppendLine("        public static IEnumerable<int> Children(int index)");
            sb.AppendLine("        {");
            sb.AppendLine("            for (int i = index + 1; i < All.Count; i++)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (All[i].ParentIndex == index) { yield return i; }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
