import { test, expect } from '@playwright/test';

/**
 * Canary for the **CPU Call Tree scoping** surface (#351 Phase 5). Loads a fixture trace carrying a
 * `CpuSampleSection`, opens the Call Tree panel, and exercises the Phase-5 toolbar: the System/Phase scope
 * selectors and the non-stationarity density sparkline render, and re-scoping via the manual range control
 * re-folds the tree (an out-of-range scope empties it; clearing the scope chip restores the whole-session tree).
 *
 * The fixture is generated by the DEBUG-only `POST /api/fixtures/trace` endpoint with
 * `variant: 'with-cpu-samples'`; nothing is committed to the repo.
 */

interface SessionSummary { sessionId: string }

async function closeAllSessions(request: import('@playwright/test').APIRequestContext): Promise<void> {
  const list = await request.get('http://localhost:5173/api/sessions');
  if (!list.ok()) return;
  const { sessions = [] } = await list.json();
  for (const s of sessions as SessionSummary[]) {
    await request.delete(`http://localhost:5173/api/sessions/${s.sessionId}`, {
      headers: { 'X-Session-Token': s.sessionId },
    });
  }
}

test.describe('Profiler — CPU Call Tree scoping (canary)', () => {
  test('scope toolbar renders; a manual range re-scopes the folded tree', async ({ page, request }) => {
    await closeAllSessions(request);

    const fx = await request.post('http://localhost:5173/api/fixtures/trace', {
      data: { variant: 'with-cpu-samples' },
    });
    expect(fx.ok(), 'fixture endpoint should respond 200').toBeTruthy();
    const { traceFilePath } = await fx.json();
    expect(traceFilePath, 'trace file path should be returned').toBeTruthy();

    await page.addInitScript(() => {
      try { localStorage.clear(); } catch { /* ignore */ }
    });
    await page.goto('/');

    await page.getByRole('button', { name: /^open \.typhon-trace$/i }).click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await page.getByRole('tab', { name: /^open trace$/i }).click();
    await page.getByPlaceholder(/\.typhon-trace or/i).fill(traceFilePath);
    await page.getByRole('button', { name: /^open$/i }).click();
    await expect(page.getByRole('dialog')).not.toBeVisible({ timeout: 10_000 });

    await page.getByRole('menuitem', { name: 'View' }).click();
    await page.getByRole('menuitem', { name: 'Call Tree' }).click();

    // The folded tree renders the fixture's three samples (whole-session scope) — the root frame
    // is shown by its friendly Type.Method name.
    await expect(page.getByText('MovementSystem.Execute', { exact: false })).toBeVisible({ timeout: 15_000 });
    await expect(page.getByText(/3 samples/i)).toBeVisible();

    // Phase-5 toolbar: the System / Phase scope selectors and the non-stationarity density sparkline.
    await expect(page.locator('select[title="Scope the call tree to a system"]')).toBeVisible();
    await expect(page.locator('select[title="Scope the call tree to a phase"]')).toBeVisible();
    await expect(page.getByText('density', { exact: true })).toBeVisible();

    // Re-scope via the manual range to a window past every sample → the tree empties and a scope chip appears.
    await page.getByPlaceholder('start').fill('999999999');
    await expect(page.getByText(/no cpu samples in the selected scope/i)).toBeVisible({ timeout: 10_000 });
    await expect(page.getByText(/^Range/)).toBeVisible();

    // Clearing the scope chip restores the whole-session tree.
    await page.getByRole('button', { name: /clear scope/i }).click();
    await expect(page.getByText(/3 samples/i)).toBeVisible({ timeout: 10_000 });

    await closeAllSessions(request);
  });
});
