import { test, expect } from '@playwright/test';

/**
 * Canary for the **CPU Call Tree** method-name filter and the frame-root **breadcrumb** drill
 * navigation (#351 follow-up UX). Loads a fixture trace carrying a `CpuSampleSection`, opens the
 * Call Tree panel, then:
 *  - filters by a substring → the tree narrows to the matching branch + a match count;
 *  - filters by a CamelCase hump (`GP` → `GetPage`) → the same;
 *  - drills into a frame via its focus button → a breadcrumb appears and the filter clears;
 *  - pops the breadcrumb's `root` crumb → the whole-session tree is restored.
 *
 * The fixture is generated by the DEBUG-only `POST /api/fixtures/trace` endpoint with
 * `variant: 'with-cpu-samples'` — three samples under `MovementSystem.Execute`, with leaf frames
 * `PagedMmf.GetPage` (×2) and `Thread.Sleep` (×1). Nothing is committed to the repo.
 */

interface SessionSummary { sessionId: string }

async function closeAllSessions(request: import('@playwright/test').APIRequestContext): Promise<void> {
  const list = await request.get('http://localhost:5173/api/sessions');
  if (!list.ok()) return;
  const { sessions = [] } = await list.json();
  for (const s of sessions as SessionSummary[]) {
    await request.delete(`http://localhost:5173/api/sessions/${s.sessionId}`, {
      headers: { 'X-Session-Token': s.sessionId },
    });
  }
}

test.describe('Profiler — CPU Call Tree filter + breadcrumb (canary)', () => {
  test('search filter narrows the tree; breadcrumb drills and restores', async ({ page, request }) => {
    await closeAllSessions(request);

    const fx = await request.post('http://localhost:5173/api/fixtures/trace', {
      data: { variant: 'with-cpu-samples' },
    });
    expect(fx.ok(), 'fixture endpoint should respond 200').toBeTruthy();
    const { traceFilePath } = await fx.json();
    expect(traceFilePath, 'trace file path should be returned').toBeTruthy();

    await page.addInitScript(() => {
      try { localStorage.clear(); } catch { /* ignore */ }
    });
    await page.goto('/');

    await page.getByRole('button', { name: /^open \.typhon-trace$/i }).click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await page.getByRole('tab', { name: /^open trace$/i }).click();
    await page.getByPlaceholder(/\.typhon-trace or/i).fill(traceFilePath);
    await page.getByRole('button', { name: /^open$/i }).click();
    await expect(page.getByRole('dialog')).not.toBeVisible({ timeout: 10_000 });

    await page.getByRole('menuitem', { name: 'View' }).click();
    await page.getByRole('menuitem', { name: 'Call Tree' }).click();

    // Whole-session tree: the root frame and both leaves (hot path auto-expands).
    await expect(page.getByText('MovementSystem.Execute', { exact: false })).toBeVisible({ timeout: 15_000 });
    await expect(page.getByText('PagedMmf.GetPage', { exact: false })).toBeVisible();
    await expect(page.getByText('Thread.Sleep', { exact: false })).toBeVisible();

    // ── Substring filter — "Sleep" narrows the tree to the Thread.Sleep branch. ──
    const filter = page.getByPlaceholder(/filter methods/i);
    await filter.fill('Sleep');
    await expect(page.getByText('Thread.Sleep', { exact: false })).toBeVisible({ timeout: 10_000 });
    await expect(page.getByText('PagedMmf.GetPage', { exact: false })).toHaveCount(0);
    await expect(page.getByText('1 match', { exact: true })).toBeVisible();

    // ── CamelCase hump — "GP" hump-matches the word "GetPage". ──
    await filter.fill('GP');
    await expect(page.getByText('PagedMmf.GetPage', { exact: false })).toBeVisible({ timeout: 10_000 });
    await expect(page.getByText('Thread.Sleep', { exact: false })).toHaveCount(0);

    // ── Drill into GetPage via its focus button → breadcrumb appears, filter clears. ──
    await page.getByRole('button', { name: /focus the call tree on PagedMmf\.GetPage/i }).click();
    const breadcrumb = page.getByRole('navigation', { name: /call tree focus/i });
    await expect(breadcrumb).toBeVisible();
    await expect(breadcrumb.getByRole('button', { name: /^root$/i })).toBeVisible();
    await expect(breadcrumb.getByText('PagedMmf.GetPage', { exact: false })).toBeVisible();
    await expect(filter, 'a drill resets the method filter').toHaveValue('');

    // ── Pop the "root" crumb → breadcrumb gone, whole-session tree restored. ──
    await breadcrumb.getByRole('button', { name: /^root$/i }).click();
    await expect(breadcrumb).toHaveCount(0);
    await expect(page.getByText('Thread.Sleep', { exact: false })).toBeVisible({ timeout: 10_000 });

    await closeAllSessions(request);
  });
});
