import { test, expect } from '@playwright/test';

/**
 * Canary for the **CPU Call Tree** panel (#351 Phase 4). Loads a fixture trace carrying a
 * `CpuSampleSection` trailer, opens the Call Tree panel via the View menu, and asserts the
 * server-folded tree renders, the view-mode toggle round-trips, and clicking a sourced frame
 * issues the `/api/profiler/open-in-editor` handoff.
 *
 * The fixture is generated by the DEBUG-only `POST /api/fixtures/trace` endpoint with
 * `variant: 'with-cpu-samples'`; nothing is committed to the repo.
 */

interface SessionSummary { sessionId: string }

async function closeAllSessions(request: import('@playwright/test').APIRequestContext): Promise<void> {
  const list = await request.get('http://localhost:5173/api/sessions');
  if (!list.ok()) return;
  const { sessions = [] } = await list.json();
  for (const s of sessions as SessionSummary[]) {
    await request.delete(`http://localhost:5173/api/sessions/${s.sessionId}`, {
      headers: { 'X-Session-Token': s.sessionId },
    });
  }
}

test.describe('Profiler — CPU Call Tree (canary)', () => {
  test('cpu-sample trace → call tree folds → frame opens source', async ({ page, request }) => {
    await closeAllSessions(request);

    const fx = await request.post('http://localhost:5173/api/fixtures/trace', {
      data: { variant: 'with-cpu-samples' },
    });
    expect(fx.ok(), 'fixture endpoint should respond 200').toBeTruthy();
    const { traceFilePath } = await fx.json();
    expect(traceFilePath, 'trace file path should be returned').toBeTruthy();

    await page.addInitScript(() => {
      try { localStorage.clear(); } catch { /* ignore */ }
    });
    await page.goto('/');

    await page.getByRole('button', { name: /^open \.typhon-trace$/i }).click();
    await expect(page.getByRole('dialog')).toBeVisible();
    await page.getByRole('tab', { name: /^open trace$/i }).click();
    await page.getByPlaceholder(/\.typhon-trace or/i).fill(traceFilePath);
    await page.getByRole('button', { name: /^open$/i }).click();
    await expect(page.getByRole('dialog')).not.toBeVisible({ timeout: 10_000 });

    // Open the Call Tree panel via the View menu — it's a dynamic center-group panel (#351 Phase 4),
    // not part of the default layout, so the folded tree gets full center width.
    await page.getByRole('menuitem', { name: 'View' }).click();
    await page.getByRole('menuitem', { name: 'Call Tree' }).click();

    // The server-folded tree renders the root frame from the fixture — shown by its friendly
    // Type.Method name (the full `AntHill.MovementSystem.Execute(...)` declaration is the tooltip).
    const rootFrame = page.getByText('MovementSystem.Execute', { exact: false });
    await expect(rootFrame).toBeVisible({ timeout: 15_000 });

    // The sample-count summary reflects the 3-sample fixture.
    await expect(page.getByText(/3 samples/i)).toBeVisible();

    // View-mode toggle round-trips: switch to On-CPU, the off-CPU sample drops out (2 samples).
    await page.getByRole('button', { name: /^on-cpu$/i }).click();
    await expect(page.getByText(/2 samples/i)).toBeVisible({ timeout: 10_000 });
    await page.getByRole('button', { name: /^wall-clock$/i }).click();
    await expect(page.getByText(/3 samples/i)).toBeVisible({ timeout: 10_000 });

    // Clicking a sourced frame fires the editor handoff.
    const handoff = page.waitForRequest((r) => r.url().includes('/api/profiler/open-in-editor') && r.method() === 'POST');
    await rootFrame.click();
    await handoff;

    await closeAllSessions(request);
  });
});
