#!/usr/bin/env python3
"""Generate the Typhon telemetry flag reference from the source of truth.

The ~200 telemetry gate flags are declared in
``src/Typhon.Engine/Observability/public/TelemetryConfig.cs`` — their config keys
and descriptions live there (in the static constructor + XML doc comments). This
script extracts them and regenerates two derived artifacts:

  * ``doc/feature-set/Observability/typhon.telemetry.template.jsonc`` — a copy-paste
    config template: the full nested tree, every flag at its real default, each with
    a ``//`` description. (JSONC — the .NET config loader skips comments.)
  * ``doc/feature-set/Observability/telemetry-flags-reference.md`` — a browsable
    doc-site page listing every flag, its default, and what it does.

Both files are GENERATED — never hand-edit them. Run this script after adding or
renaming a flag. CI runs it with ``--check`` and fails if the committed files drift
from the source (see scripts wiring / the doc-accuracy design doc).

    python3 scripts/gen-telemetry-reference.py           # regenerate (writes files)
    python3 scripts/gen-telemetry-reference.py --check    # verify freshness (CI gate)
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import OrderedDict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
# The single source of truth (#522). The legacy hand-written class no longer carries the flag tree — it is
# generated from this catalog by Typhon.Generators.Telemetry. SRC is retained only for the one-time bootstrap
# (scripts/bootstrap-telemetry-catalog.py --source <old TelemetryConfig.cs>).
CATALOG = REPO / "src" / "Typhon.Engine" / "Observability" / "telemetry-flags.jsonc"
SRC = REPO / "src" / "Typhon.Engine" / "Observability" / "public" / "TelemetryConfig.cs"
OUT_JSONC = REPO / "doc" / "feature-set" / "Observability" / "typhon.telemetry.template.jsonc"
OUT_MD = REPO / "doc" / "feature-set" / "Observability" / "telemetry-flags-reference.md"

GEN_BANNER = "GENERATED by scripts/gen-telemetry-reference.py from telemetry-flags.jsonc — do not hand-edit."


# ── description extraction ──────────────────────────────────────────────────────

def clean_desc(raw: str) -> str:
    """Turn an XML ``<summary>`` body into a one-line plain-text description."""
    s = raw
    # <see cref="A.B.C"/> -> C  (last dotted segment)
    s = re.sub(r'<see\s+cref="([^"]+)"\s*/>', lambda m: m.group(1).split(".")[-1].split(":")[-1], s)
    # <c>x</c> / <b>x</b> / <i>x</i> -> x
    s = re.sub(r"</?(?:c|b|i|para|remarks|list|item)[^>]*>", "", s)
    # any remaining tags
    s = re.sub(r"<[^>]+>", "", s)
    s = s.replace("///", " ")
    s = re.sub(r"\s+", " ", s).strip()
    # the config key is redundant in a template keyed by that very path — drop it.
    s = re.sub(r"\s*Reads from [^.]*\.?", "", s, flags=re.IGNORECASE).strip()
    return s


def parse_field_summaries(text: str) -> dict[str, str]:
    """Map ``public static readonly bool <Field>`` -> cleaned <summary> description."""
    out: dict[str, str] = {}
    pat = re.compile(
        r"((?:[ \t]*///.*\r?\n)+)[ \t]*public static readonly bool (\w+)\s*;"
    )
    for m in pat.finditer(text):
        block, field = m.group(1), m.group(2)
        sm = re.search(r"<summary>(.*?)</summary>", block, flags=re.DOTALL)
        body = sm.group(1) if sm else block
        out[field] = clean_desc(body)
    return out


# ── config-key extraction from the static constructor ───────────────────────────

class Entry:
    __slots__ = ("key", "default", "desc", "order")

    def __init__(self, key: str, default: bool, desc: str, order: int):
        self.key = key
        self.default = default
        self.desc = desc
        self.order = order


def parse_keys(text: str, summaries: dict[str, str]) -> list[Entry]:
    """Extract every settable ``Typhon:...:Enabled`` config key, in source order."""
    ctor = text[text.index("static TelemetryConfig()"):]

    # mapvar -> "Typhon:Profiler" prefix used when the Node tree was resolved.
    prefixes: dict[str, str] = {}
    for m in re.finditer(
        r"(\w+)\s*=\s*TelemetryConfigResolver\.Resolve\((?:.*?)\"([^\"]+)\"\s*\)\s*;",
        ctor,
        flags=re.DOTALL,
    ):
        prefixes[m.group(1)] = m.group(2)

    found: "OrderedDict[str, Entry]" = OrderedDict()
    order = 0

    def add(key: str, default: bool, lhs: str | None):
        nonlocal order
        if not (key.startswith("Typhon:") and key.endswith(":Enabled")):
            return
        desc = summaries.get(lhs or "", "") if lhs else ""
        if key in found:
            e = found[key]
            if not e.desc and desc:
                e.desc = desc
            # a real per-key default (ReadBool) beats the tree baseline of false
            if default:
                e.default = True
        else:
            found[key] = Entry(key, default, desc, order)
            order += 1

    # 1) direct `<lhs> = ReadBool(config, "Typhon:...:Enabled", <default>)`
    for m in re.finditer(
        r"(\w+)\s*=\s*ReadBool\(\s*config\s*,\s*\"([^\"]+)\"\s*,\s*(true|false)\s*\)",
        ctor,
    ):
        add(m.group(2), m.group(3) == "true", m.group(1))

    # 2) `<lhs> = <mapvar>["path"]` -> key = <prefix>:<path>:Enabled (tree nodes, default off)
    for m in re.finditer(r"(\w+)\s*=\s*(\w+)\[\"([^\"]+)\"\]\s*;", ctor):
        lhs, mapvar, path = m.group(1), m.group(2), m.group(3)
        if mapvar in prefixes:
            add(f"{prefixes[mapvar]}:{path}:Enabled", False, lhs)

    return sorted(found.values(), key=lambda e: e.order)


# ── tree assembly ───────────────────────────────────────────────────────────────

class Node:
    __slots__ = ("kids", "toggle")

    def __init__(self):
        self.kids: "OrderedDict[str, Node]" = OrderedDict()
        self.toggle: tuple[bool, str] | None = None  # (default, description)

    def child(self, name: str) -> "Node":
        if name not in self.kids:
            self.kids[name] = Node()
        return self.kids[name]


def build_tree(entries: list[Entry]) -> Node:
    root = Node()
    for e in entries:
        segs = e.key[: -len(":Enabled")].split(":")  # drop trailing Enabled
        node = root
        for seg in segs:
            node = node.child(seg)
        node.toggle = (e.default, e.desc)
    return root


# ── emitters ────────────────────────────────────────────────────────────────────

def emit_jsonc(root: Node) -> str:
    lines = [
        f"// {GEN_BANNER}",
        "// Copy to `typhon.telemetry.json` (or keep the .jsonc — the loader skips comments),",
        "// then flip the flags you want to observe. Env vars override: TYPHON__PROFILER__…__ENABLED=true.",
        "// Parent-implies-children: enabling a subtree's root enables all its leaves unless a leaf is set false.",
    ]

    def walk(name: str, node: Node, indent: int, last: bool):
        pad = "  " * indent
        lines.append(f'{pad}"{name}": {{')
        inner = "  " * (indent + 1)
        if node.toggle is not None:
            default, desc = node.toggle
            if desc:
                lines.append(f"{inner}// {desc}")
            lines.append(f'{inner}"Enabled": {"true" if default else "false"},')
        kid_items = list(node.kids.items())
        for i, (kname, kn) in enumerate(kid_items):
            walk(kname, kn, indent + 1, i == len(kid_items) - 1)
        lines.append(f"{pad}}},")

    lines.append("{")
    top = list(root.kids.items())
    for i, (name, node) in enumerate(top):
        walk(name, node, 1, i == len(top) - 1)
    lines.append("}")
    return "\n".join(lines) + "\n"


def emit_md(entries: list[Entry], jsonc: str) -> str:
    # group by the segment after "Typhon:Profiler:" (e.g. Concurrency, Spatial …);
    # bare Typhon:Profiler:* leaves bucket under "Profiler (top level)".
    groups: "OrderedDict[str, list[Entry]]" = OrderedDict()
    for e in entries:
        segs = e.key.split(":")
        group = segs[2] if len(segs) > 3 else "Profiler (top level)"
        groups.setdefault(group, []).append(e)

    total = len(entries)
    out: list[str] = []
    out.append("---")
    out.append("uid: feature-observability-telemetry-flags-reference")
    out.append("title: 'Telemetry Flags Reference (generated)'")
    out.append(
        "description: 'The complete, generated list of every Typhon telemetry gate flag — "
        f"config key, default, and what it enables ({total} flags). Generated from telemetry-flags.jsonc.'"
    )
    out.append("---")
    out.append("")
    out.append("# Telemetry Flags Reference")
    out.append("")
    out.append(f"> **{total} flags.** {GEN_BANNER}")
    out.append("")
    out.append(
        "Every gate that controls Typhon's [distributed tracing](xref:feature-observability-distributed-tracing) "
        "and [typed-event Profiler](../Profiler/README.md). All default **off** unless noted; enabling a subtree's "
        "root enables its leaves ([parent-implies-children](xref:feature-observability-telemetry-config-gating)). "
        "Set them in `typhon.telemetry.json` or via `TYPHON__…__ENABLED` environment variables."
    )
    out.append("")
    out.append("## Copy-paste template")
    out.append("")
    out.append("Copy this into `typhon.telemetry.json` (the loader skips comments and trailing commas) and flip what you "
               "need. It also ships verbatim as `typhon.telemetry.template.jsonc` next to this page in the repo.")
    out.append("")
    out.append("```jsonc")
    out.append(jsonc.rstrip("\n"))
    out.append("```")
    out.append("")
    out.append("## All flags")
    out.append("")
    for group, items in groups.items():
        out.append(f"### {group}")
        out.append("")
        out.append("| Config key | Default | Enables |")
        out.append("|---|---|---|")
        for e in items:
            desc = e.desc.replace("|", "\\|") if e.desc else "—"
            out.append(f"| `{e.key}` | `{str(e.default).lower()}` | {desc} |")
        out.append("")
    return "\n".join(out)


# ── driver ──────────────────────────────────────────────────────────────────────

# ── catalog reader (the source of truth is now the JSONC catalog, not the C# ctor) ──────────────

def _strip_jsonc(s: str) -> str:
    """Remove ``//`` line comments (respecting string literals) and trailing commas."""
    out: list[str] = []
    i, n, instr = 0, len(s), False
    while i < n:
        c = s[i]
        if instr:
            out.append(c)
            if c == "\\" and i + 1 < n:
                out.append(s[i + 1]); i += 2; continue
            if c == '"':
                instr = False
            i += 1; continue
        if c == '"':
            instr = True; out.append(c); i += 1; continue
        if c == "/" and i + 1 < n and s[i + 1] == "/":
            while i < n and s[i] != "\n":
                i += 1
            continue
        out.append(c); i += 1
    return re.sub(r",(\s*[}\]])", r"\1", "".join(out))


def read_catalog() -> list[Entry]:
    """Flatten the JSONC catalog into settable ``Entry`` records (one per keyed flag), in source order."""
    data = json.loads(_strip_jsonc(CATALOG.read_text(encoding="utf-8")))
    prefix = data["prefix"]
    entries: list[Entry] = []
    order = [0]

    def walk(node: dict, path: str):
        key = f"{prefix}:Enabled" if path == "" else f"{prefix}:{path}:Enabled"
        if node.get("kind") != "group":
            entries.append(Entry(key, bool(node.get("default", False)), node.get("desc", "") or "", order[0]))
            order[0] += 1
        for child in node.get("children", []):
            child_path = child["name"] if path == "" else f"{path}:{child['name']}"
            walk(child, child_path)

    walk(data["root"], "")
    return entries


def generate() -> dict[Path, str]:
    entries = read_catalog()
    if not entries:
        print("ERROR: no telemetry flags in the catalog — did telemetry-flags.jsonc move or change shape?", file=sys.stderr)
        sys.exit(2)
    tree = build_tree(entries)
    jsonc = emit_jsonc(tree)
    return {OUT_JSONC: jsonc, OUT_MD: emit_md(entries, jsonc)}


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate the telemetry flag reference from TelemetryConfig.cs.")
    ap.add_argument("--check", action="store_true", help="Verify committed files are up to date; exit 1 on drift.")
    args = ap.parse_args()

    artifacts = generate()

    if args.check:
        stale = []
        for path, content in artifacts.items():
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != content:
                stale.append(path.relative_to(REPO))
        if stale:
            print("Telemetry reference is STALE — run: python3 scripts/gen-telemetry-reference.py", file=sys.stderr)
            for p in stale:
                print(f"  drift: {p}", file=sys.stderr)
            return 1
        n = sum(1 for _ in artifacts)
        print(f"Telemetry reference up to date ({n} files).")
        return 0

    for path, content in artifacts.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
